name: Test Action
on: [push]

jobs:
    test-job:
        name: Test Job
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v2
            
          - name: Print app.js
            run: cat src/frontend/app.js
